#!/bin/bash

gsettings set org.gnome.shell.extensions.dash-to-dock hot-keys false

gsettings set org.gnome.shell.keybindings switch-to-application-1 "['']"
gsettings set org.gnome.shell.keybindings switch-to-application-2 "['']"
gsettings set org.gnome.shell.keybindings switch-to-application-3 "['']"
gsettings set org.gnome.shell.keybindings switch-to-application-4 "['']"
gsettings set org.gnome.shell.keybindings switch-to-application-5 "['']"
gsettings set org.gnome.shell.keybindings switch-to-application-6 "['']"
gsettings set org.gnome.shell.keybindings switch-to-application-7 "['']"
       
gsettings set org.gnome.shell.extensions.dash-to-dock app-hotkey-1 "['']"
gsettings set org.gnome.shell.extensions.dash-to-dock app-hotkey-2 "['']"
gsettings set org.gnome.shell.extensions.dash-to-dock app-hotkey-3 "['']"
gsettings set org.gnome.shell.extensions.dash-to-dock app-hotkey-4 "['']"
gsettings set org.gnome.shell.extensions.dash-to-dock app-hotkey-5 "['']"
gsettings set org.gnome.shell.extensions.dash-to-dock app-hotkey-6 "['']"
gsettings set org.gnome.shell.extensions.dash-to-dock app-hotkey-7 "['']"
gsettings set org.gnome.shell.extensions.dash-to-dock app-hotkey-8 "['']"
